In [2]:
import pandas as pd

# Atividades

In [13]:
df_atividades =pd.read_csv('atividades.csv')
df_atividades.head()

   id_oferta nivel_dificuldade  duracao  grupo_maximo
0          1           Difícil        3            19
1          3             Fácil        1             9
2          6           Difícil        4             8
3          8           Difícil        9            15
4         10             Fácil        3            14

In [8]:
pd.DataFrame({
    'Tipo de dado': df_atividades.dtypes,
    'Quantidade de nulos': df_atividades.isnull().sum(),
    'Percentual de nulos': df_atividades.isnull().mean()*100,
    'Qtde valores únicos': df_atividades.nunique(),
    'Exemplos valores únicos': df_atividades.apply(lambda x: x.unique()[:5])
})

,Tipo de dado,Quantidade de nulos,Percentual de nulos,Qtde valores únicos,Exemplos valores únicos
id_oferta,int64,0,0.0,580,"[1, 3, 6, 8, 10]"
nivel_dificuldade,object,0,0.0,3,"[Difícil, Fácil, Médio]"
duracao,int64,0,0.0,9,"[3, 1, 4, 9, 7]"
grupo_maximo,int64,0,0.0,16,"[19, 9, 8, 15, 14]"

In [10]:
df_atividades.shape

(580, 4)

In [11]:
df_atividades.describe()

         id_oferta     duracao  grupo_maximo
count   580.000000  580.000000    580.000000
mean    598.912069    4.908621     12.415517
std     337.587582    2.576685      4.507308
min       1.000000    1.000000      5.000000
25%     321.500000    3.000000      9.000000
50%     590.500000    5.000000     13.000000
75%     884.500000    7.000000     16.000000
max    1200.000000    9.000000     20.000000

# Avaliações

In [15]:
df_avaliacoes = pd.read_csv('avaliacoes.csv')
df_avaliacoes.head()

,id_avaliacao,id_cliente,id_oferta,nota,comentario,data_avaliacao
0,1,1499,805,4,"Lorem ipsum dolor sit amet, consectetur adipis...",2025-05-30
1,2,1499,805,4,Integer ut lectus id libero volutpat varius.,2025-05-21
2,3,1499,805,4,"Ut enim ad minim veniam, quis nostrud exercita...",2025-05-26
3,4,1499,805,3,"Lorem ipsum dolor sit amet, consectetur adipis...",2025-05-22
4,5,170,975,1,"Curabitur pretium tincidunt lacus, nec volutpa...",2024-11-14

In [17]:
pd.DataFrame({
    'Tipo de dado': df_avaliacoes.dtypes,
    'Quantidade de nulos': df_avaliacoes.isnull().sum(),
    'Percentual de nulos': df_avaliacoes.isnull().mean()*100,
    'Qtde valores únicos': df_avaliacoes.nunique(),
    'Exemplos valores únicos': df_avaliacoes.apply(lambda x: x.unique()[:6])
})

,Tipo de dado,Quantidade de nulos,Percentual de nulos,Qtde valores únicos,Exemplos valores únicos
id_avaliacao,int64,0,0.0,2394,"[1, 2, 3, 4, 5, 6]"
id_cliente,int64,0,0.0,614,"[1499, 170, 1028, 50, 92, 320]"
id_oferta,int64,0,0.0,573,"[805, 975, 890, 625, 479, 176]"
nota,int64,0,0.0,5,"[4, 3, 1, 2, 5]"
comentario,object,0,0.0,10,"[Lorem ipsum dolor sit amet, consectetur adipi..."
data_avaliacao,object,0,0.0,365,"[2025-05-30, 2025-05-21, 2025-05-26, 2025-05-2..."

In [19]:
df_avaliacoes.shape

(2394, 6)

In [21]:
df_avaliacoes.describe()

       id_avaliacao   id_cliente    id_oferta         nota
count   2394.000000  2394.000000  2394.000000  2394.000000
mean    1197.500000   752.100251   587.482874     2.989140
std      691.232595   433.276289   348.356315     1.397825
min        1.000000     1.000000     1.000000     1.000000
25%      599.250000   355.000000   283.000000     2.000000
50%     1197.500000   754.000000   581.000000     3.000000
75%     1795.750000  1145.750000   888.000000     4.000000
max     2394.000000  1499.000000  1198.000000     5.000000

# Clientes

In [24]:
df_clientes = pd.read_csv('clientes.csv')
df_clientes.head()

,id_cliente,nome,email,data_nascimento,genero,localidade
0,1,Ana Sophia Araújo,levicunha@ig.com.br,1951-05-31,Masculino,Pereira
1,2,Antônio Carvalho,claricearaujo@viana.br,1984-07-15,Masculino,Almeida da Serra
2,3,Sra. Heloísa Freitas,sarahmendes@carvalho.com,1968-11-12,Feminino,Ferreira do Norte
3,4,Sra. Maria Alice Costa,vieiranicolas@ig.com.br,1986-07-12,Masculino,da Mota de Minas
4,5,Rafael Dias,diaseduardo@uol.com.br,1963-05-10,Masculino,Moreira de da Cruz

In [27]:
pd.DataFrame({
    'Tipo de dado': df_clientes.dtypes,
    'Quantidade de nulos': df_clientes.isnull().sum(),
    'Percentual de nulos': df_clientes.isnull().mean()*100,
    'Qtde valores únicos': df_clientes.nunique(),
    'Exemplos valores únicos': df_clientes.apply(lambda x: x.unique()[:5])
})

,Tipo de dado,Quantidade de nulos,Percentual de nulos,Qtde valores únicos,Exemplos valores únicos
id_cliente,int64,0,0.0,1500,"[1, 2, 3, 4, 5]"
nome,object,0,0.0,1452,"[Ana Sophia Araújo, Antônio Carvalho, Sra. Hel..."
email,object,0,0.0,1500,"[levicunha@ig.com.br, claricearaujo@viana.br, ..."
data_nascimento,object,0,0.0,1452,"[1951-05-31, 1984-07-15, 1968-11-12, 1986-07-1..."
genero,object,0,0.0,2,"[Masculino, Feminino]"
localidade,object,0,0.0,752,"[Pereira, Almeida da Serra, Ferreira do Norte,..."

In [29]:
df_clientes.shape

(1500, 6)

In [30]:
df_clientes.describe()

        id_cliente
count  1500.000000
mean    750.500000
std     433.157015
min       1.000000
25%     375.750000
50%     750.500000
75%    1125.250000
max    1500.000000

# Hospedagens

In [32]:
df_hospedagens = pd.read_csv('hospedagens.csv')
df_hospedagens.head()

   id_oferta   tipo_acomodacao  capacidade  possui_cafe_manha
0          2  Casa de hóspedes           5                1.0
1          4       Apartamento           4                1.0
2          5             Chalé           7                1.0
3          7  Casa de hóspedes           6                NaN
4          9  Casa de hóspedes           2                1.0

In [34]:
pd.DataFrame({
    'Tipo de dado': df_hospedagens.dtypes,
    'Quantidade de nulos': df_hospedagens.isnull().sum(),
    'Percentual de nulos': df_hospedagens.isnull().mean()*100,
    'Qtde valores únicos': df_hospedagens.nunique(),
    'Exemplos valores únicos': df_hospedagens.apply(lambda x: x.unique()[:5])
})

,Tipo de dado,Quantidade de nulos,Percentual de nulos,Qtde valores únicos,Exemplos valores únicos
id_oferta,int64,0,0.00000,620,"[2, 4, 5, 7, 9]"
tipo_acomodacao,object,0,0.00000,4,"[Casa de hóspedes, Apartamento, Chalé, Quarto ..."
capacidade,int64,0,0.00000,9,"[5, 4, 7, 6, 2]"
possui_cafe_manha,float64,309,49.83871,1,"[1.0, nan]"

In [36]:

df_hospedagens.shape

(620, 4)

In [37]:

df_hospedagens.describe()

         id_oferta  capacidade  possui_cafe_manha
count   620.000000  620.000000              311.0
mean    601.985484    5.027419                1.0
std     355.003736    2.492812                0.0
min       2.000000    1.000000                1.0
25%     287.750000    3.000000                1.0
50%     612.000000    5.000000                1.0
75%     916.500000    7.000000                1.0
max    1198.000000    9.000000                1.0

# Ofertas Práticas

In [39]:
df_oferta_pratica = pd.read_csv('oferta_pratica.csv')
df_oferta_pratica.head()

   id_oferta  id_pratica
0          1          39
1          1           8
2          1          47
3          7          19
4          7          15

In [41]:

df_oferta_pratica.shape

(2436, 2)

In [43]:
df_oferta_pratica.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2436 entries, 0 to 2435
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_oferta   2436 non-null   int64
 1   id_pratica  2436 non-null   int64
dtypes: int64(2)
memory usage: 38.2 KB

In [44]:
df_oferta_pratica.nunique()

id_oferta     802
id_pratica     50
dtype: int64

# Ofertas

In [45]:
df_ofertas = pd.read_csv('ofertas.csv')
df_ofertas.head()

,id_oferta,tipo_oferta,titulo,descricao,preco,id_operador
0,1,atividade,Atividade Oferta 1,Placeat quia sint facere eveniet soluta quis. ...,106.80,31
1,2,hospedagem,Hospedagem Oferta 2,Dolorum illo a neque. Fugit quidem occaecati r...,212.97,73
2,3,atividade,Atividade Oferta 3,Ex consequuntur nemo rem corrupti. Deleniti ea...,322.29,87
3,4,hospedagem,Hospedagem Oferta 4,Sunt quam repellat provident molestiae. Porro ...,476.97,48
4,5,hospedagem,Hospedagem Oferta 5,Nulla voluptatibus nam consequuntur. Autem bla...,393.39,74

In [46]:
pd.DataFrame({
    'Tipo de dado': df_ofertas.dtypes,
    'Quantidade de nulos': df_ofertas.isnull().sum(),
    'Percentual de nulos': df_ofertas.isnull().mean()*100,
    'Qtde valores únicos': df_ofertas.nunique(),
    'Exemplos valores únicos': df_ofertas.apply(lambda x: x.unique()[:5])
})

,Tipo de dado,Quantidade de nulos,Percentual de nulos,Qtde valores únicos,Exemplos valores únicos
id_oferta,int64,0,0.0,1200,"[1, 2, 3, 4, 5]"
tipo_oferta,object,0,0.0,2,"[atividade, hospedagem]"
titulo,object,0,0.0,1200,"[Atividade Oferta 1, Hospedagem Oferta 2, Ativ..."
descricao,object,0,0.0,1200,[Placeat quia sint facere eveniet soluta quis....
preco,float64,0,0.0,1191,"[106.8, 212.97, 322.29, 476.97, 393.39]"
id_operador,int64,0,0.0,100,"[31, 73, 87, 48, 74]"

In [47]:
df_ofertas.shape

(1200, 6)

In [48]:

df_ofertas.describe()

         id_oferta        preco  id_operador
count  1200.000000  1200.000000  1200.000000
mean    600.500000   274.751767    52.566667
std     346.554469   130.125702    28.731083
min       1.000000    50.310000     1.000000
25%     300.750000   159.515000    28.000000
50%     600.500000   275.890000    53.000000
75%     900.250000   392.165000    77.000000
max    1200.000000   499.080000   100.000000

#  Operadores

In [50]:
df_operadores = pd.read_csv('operadores.csv')
df_operadores.head()

,id_operador,nome_fantasia,cnpj,telefone,email,localidade
0,1,Porto,26.426.121/2038-43,(081) 5365-9680,luana25@yahoo.com.br,Lima
1,2,Costa Dias - EI,54.540.064/4547-52,+55 (081) 1123-2748,portoana-laura@uol.com.br,Farias
2,3,da Cunha,72.038.862/1750-80,+55 (084) 9630 4530,pietroviana@bol.com.br,Fogaça
3,4,Melo Dias Ltda.,00.181.677/8481-65,+55 (051) 4445-4460,maria-sophia17@porto.com,Duarte do Campo
4,5,Teixeira Ramos - EI,84.869.996/9882-90,(041) 5792 7147,vitor-gabriel30@viana.br,da Luz Paulista

In [52]:
pd.DataFrame({
    'Tipo de dado': df_operadores.dtypes,
    'Quantidade de nulos': df_operadores.isnull().sum(),
    'Percentual de nulos': df_operadores.isnull().mean()*100,
    'Qtde valores únicos': df_operadores.nunique(),
    'Exemplos valores únicos': df_operadores.apply(lambda x: x.unique())
})

,Tipo de dado,Quantidade de nulos,Percentual de nulos,Qtde valores únicos,Exemplos valores únicos
id_operador,int64,0,0.0,100,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
nome_fantasia,object,0,0.0,87,"[Porto, Costa Dias - EI, da Cunha, Melo Dias L..."
cnpj,object,0,0.0,100,"[26.426.121/2038-43, 54.540.064/4547-52, 72.03..."
telefone,object,0,0.0,100,"[(081) 5365-9680, +55 (081) 1123-2748, +55 (08..."
email,object,0,0.0,100,"[luana25@yahoo.com.br, portoana-laura@uol.com...."
localidade,object,0,0.0,85,"[Lima, Farias, Fogaça, Duarte do Campo, da Luz..."

In [53]:
df_operadores.shape

(100, 6)

In [55]:
df_operadores.to_csv('operadores.csv', index=False)

# Práticas sustentáveis

In [56]:
df_praticas_sustentaveis = pd.read_csv('praticas_sustentaveis.csv')
df_praticas_sustentaveis.head()

   id_pratica                               nome
0           1          Captação de água da chuva
1           2  Compostagem de resíduos orgânicos
2           3               Agricultura orgânica
3           4          Reutilização de materiais
4           5                Uso de lâmpadas LED

In [57]:
pd.DataFrame({
    'Tipo de dado': df_praticas_sustentaveis.dtypes,
    'Quantidade de nulos': df_praticas_sustentaveis.isnull().sum(),
    'Percentual de nulos': df_praticas_sustentaveis.isnull().mean()*100,
    'Qtde valores únicos': df_praticas_sustentaveis.nunique()
})

,Tipo de dado,Quantidade de nulos,Percentual de nulos,Qtde valores únicos
id_pratica,int64,0,0.0,50
nome,object,0,0.0,50

In [58]:

df_praticas_sustentaveis.shape

(50, 2)

In [59]:
df_praticas_sustentaveis.to_csv('praticas_sustentaveis.csv', index=False)

# Reservas

In [61]:
df_reservas = pd.read_csv('reservas.csv')
df_reservas.head()

,id_reserva,id_cliente,id_oferta,data_reserva,data_experiencia,qtd_pessoas,status
0,1,784,111,2024-11-30,2025-06-17,3,cancelada
1,2,654,1106,2024-12-25,2025-01-28,5,confirmada
2,3,1029,453,2025-04-14,2025-06-17,2,confirmada
3,4,1499,805,2025-04-15,2025-05-15,4,concluída
4,5,1179,1034,2024-12-30,2025-01-17,1,confirmada

In [63]:
pd.DataFrame({
    'Tipo de dado': df_reservas.dtypes,
    'Quantidade de nulos': df_reservas.isnull().sum(),
    'Percentual de nulos': df_reservas.isnull().mean()*100,
    'Qtde valores únicos': df_reservas.nunique(),
    'Exemplos valores únicos': df_reservas.apply(lambda x: x.unique())
})

,Tipo de dado,Quantidade de nulos,Percentual de nulos,Qtde valores únicos,Exemplos valores únicos
id_reserva,int64,0,0.0,2000,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
id_cliente,int64,0,0.0,1101,"[784, 654, 1029, 1499, 1179, 594, 170, 1123, 1..."
id_oferta,int64,0,0.0,984,"[111, 1106, 453, 805, 1034, 808, 975, 818, 890..."
data_reserva,object,0,0.0,366,"[2024-11-30, 2024-12-25, 2025-04-14, 2025-04-1..."
data_experiencia,object,0,0.0,332,"[2025-06-17, 2025-01-28, 2025-05-15, 2025-01-1..."
qtd_pessoas,int64,0,0.0,5,"[3, 5, 2, 4, 1]"
status,object,0,0.0,3,"[cancelada, confirmada, concluída]"

In [65]:

df_reservas.shape

(2000, 7)

In [66]:
df_reservas.describe()

        id_reserva   id_cliente    id_oferta  qtd_pessoas
count  2000.000000  2000.000000  2000.000000  2000.000000
mean   1000.500000   766.787000   599.235000     2.922000
std     577.494589   432.876375   349.354505     1.386679
min       1.000000     1.000000     1.000000     1.000000
25%     500.750000   385.000000   287.750000     2.000000
50%    1000.500000   777.500000   603.500000     3.000000
75%    1500.250000  1149.250000   900.250000     4.000000
max    2000.000000  1500.000000  1200.000000     5.000000

In [67]:
df_reservas[df_reservas['data_experiencia'] < df_reservas['data_reserva']]

Empty DataFrame
Columns: [id_reserva, id_cliente, id_oferta, data_reserva, data_experiencia, qtd_pessoas, status]
Index: []

In [68]:
df_reservas.to_csv('reservas.csv', index=False)